### ISSUE TITLE
To pass request to RabbitMq

### ISSUE THREAD

**Issue by empitegayan** [lukeautry/tsoa-example#2]
Is it possible to pass this api request to rabbitmq ?

**Comment by lukeautry** [comment]
Do you mean using node.js as a proxy for rabbitmq? Sure, you can do whatever you want in the body of the methods. Obviously, you'd have to do a lot of work to manually convert the requests coming into node to whatever format rabbitmq wants them in.

**Comment by empitegayan** [comment]
OK thank you
