### ISSUE TITLE
doesn't build?

### ISSUE THREAD

**Issue by njs50** [lukeautry/tsoa-example#3]
after `npm install` on a fresh clone trying to `npm run build` fails during both swagger-gen and routes-gen with:

```Error: Error generate parameter method: 'AccountsController.current' argument: someFlag Error: Parameter 'someFlag' can't macth in path: '/Current'```

I tried updating the deps in package.json and that just ended up with me having a type conflict between the Account model and an Account type in node_modules someplace

**Comment by lukeautry** [comment]
Fixed in #4
